# Solución de ecuaciones lineales simultáneas

Supongamos que queremos resolver un sistema de ecuaciones simultáneas para determinar las variables w,x,y y z, de:

\begin{eqnarray}
2w+x+4y+z &=&-4\\
3w+4x-y-z &=&3\\
w-4x+y+5z=9\\
2w-2x+y+3z=7
\end{eqnarray}

De acuerdo a lo que sabemos, planteamos la matriz correspondiente

$\begin{bmatrix}2 & 1 & 4 & 1 \\ 3 & 4 & -1 & -1 \\ 1 & -4 & 1 & 5 \\ 2 & -2 & 1 &3 \end{bmatrix}$ 
$\begin{bmatrix}w  \\ x \\ y \\ z \end{bmatrix}$ = 
$\begin{bmatrix} -4  \\ 3 \\ 9 \\ 7 \end{bmatrix}$ 

Que en corto, tiene la forma 

$$Ax=v$$

Una manera típica de resolver este problema es usar Eliminación Gaussiana

Tenemos 3 operaciones básicas:

1. Multiplicar un renglón por una constante
2. Suma de renglones
3. Intercambio de renglones

Con estas tres operaciones, tenemos llevamos a A a una triangular superior. De ahí usamos el método de sustitución para atras:

In [135]:
from numpy import array, zeros
A=array([[2,1,4,1],[3,4,-1,-1],[1,-4,1,5],[2,-2,1,3]],float)
c=array([-4,3,9,7],float)
n=len(c)
for i in range(n):
    for j in range(i+1,n):
        multi=(A[j,i]/A[i,i])
        A[j]=A[j]-multi*A[i]
        c[j]=c[j]-multi*c[i]
        #print('La Matriz aumentada con (%d,%d) es: ' %(i,j))
        #print(A,c)
for i in range(n):
    div=A[i,i]
    A[i]=A[i]/div
    c[i]=c[i]/div
    #print('La Matriz aumentada con el renglon %d cambiado  es:' %(i))
    #print(A,c)


x=zeros(n,float)
for j in range(n-1,-1,-1): #ciclo hacia atras
    x[j]=c[j]
    for k in range(j+1,n):
        x[j]-=A[j,k]*x[k]
print('El vector solución es')
print(x)

m=matrix([[1,2,-3,-1],[0,-3,2,6],[-3,-1,3,1],[2,3,2,-1]],float)
n=matrix([[0],[-8],[0],[-8]],float)

from numpy.linalg import solve
A=array([[2,1,4,1],[3,4,-1,-1],[1,-4,1,5],[2,-2,1,3]],float)
c=array([-4,3,9,7],float)
print('La solucion con numpy es: ',solve(A,c))

El vector solución es
[ 2. -1. -2.  1.]
La solucion con numpy es:  [ 2. -1. -2.  1.]


# Matriz inversa con Gauss-Jordan

In [136]:
from numpy import array, zeros, eye

A=matrix([[1,2,-3,-1],[0,-3,2,6],[-3,-1,3,1],[2,3,2,-1]],float)
#A=array([[2,1,4,1],[3,4,-1,-1],[1,-4,1,5],[2,-2,1,3]],float)
n=len(A)
c =eye(n)

for i in range(n):
    for j in range(n):
        if A[i,i]!=0 and i!=j:
            multi=(A[j,i]/A[i,i])
            A[j]=A[j]-multi*A[i]
            c[j]=c[j]-multi*c[i]
for i in range(n):
    div=A[i,i]
    A[i]=A[i]/div
    c[i]=c[i]/div        

print('La Matriz original queda como')
print(array(A,int))
print('La Matriz inversa queda como')
print(c)


La Matriz original queda como
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
La Matriz inversa queda como
[[-0.2797619   0.0297619  -0.36309524  0.0952381 ]
 [ 0.44047619  0.05952381  0.27380952  0.19047619]
 [-0.23214286 -0.01785714  0.01785714  0.14285714]
 [ 0.29761905  0.20238095  0.13095238  0.04761905]]


In [137]:
#Comprobación con Numpy

from numpy.linalg import *
A=array([[2,1,4,1],[3,4,-1,-1],[1,-4,1,5],[2,-2,1,3]],float)
A_inv=inv(A)
print('La inversa es: ',array(A_inv,float))
print(array(dot(A,A_inv),int))
#print(dot(A,A_inv))

La inversa es:  [[-1.17647059e-01 -5.88235294e-02 -5.88235294e-01  1.00000000e+00]
 [ 1.76470588e-01  3.38235294e-01  6.32352941e-01 -1.00000000e+00]
 [ 2.35294118e-01 -1.32352941e-01 -7.35294118e-02 -1.30614473e-17]
 [ 1.17647059e-01  3.08823529e-01  8.38235294e-01 -1.00000000e+00]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


###  Nuestra propia funcion Gauss_Jordan

In [143]:
from numpy import *
from numpy.linalg import *

def gauss_jordan(A):
    A_copia=A.copy()
    n=len(A)
    c =eye(n)
    c_copia=c.copy()
    for i in range(n):
        for j in range(n):
            if A_copia[i,i]!=0 and i!=j:
                multi=(A_copia[j,i]/A_copia[i,i])
                A_copia[j]=A_copia[j]-multi*A_copia[i]
                c_copia[j]=c_copia[j]-multi*c_copia[i]
    for i in range(n):
        div=A_copia[i,i]
        A_copia[i]=A_copia[i]/div
        c_copia[i]=c_copia[i]/div   
    return c_copia
    
B=array([[2,1,4,1],
         [3,4,-1,-1],
         [1,-4,1,5],
         [2,-2,1,3]],float)

A1 = array([[ 4,-1,-1,-1 ],
           [ -1,0,3,0 ],
           [ -1,3,1,-1 ],
           [ -1,-1,0,4]], float)

print(B)
B_inv=gauss_jordan(B)
print('La Matriz inversa es:\n',B_inv)
print('Comprobación de que si es la inversa:')
#print(dot(B,c))
print(array(dot(B,B_inv),int))
'''

c1=gauss_jordan(A1)
print('La Matriz inversa es:\n',c1)
print('Comprobación de que si es la inversa:')
print(array(dot(A1,c1),int))
'''

[[ 2.  1.  4.  1.]
 [ 3.  4. -1. -1.]
 [ 1. -4.  1.  5.]
 [ 2. -2.  1.  3.]]
La Matriz inversa es:
 [[-0.11764706 -0.05882353 -0.58823529  1.        ]
 [ 0.17647059  0.33823529  0.63235294 -1.        ]
 [ 0.23529412 -0.13235294 -0.07352941 -0.        ]
 [ 0.11764706  0.30882353  0.83823529 -1.        ]]
Comprobación de que si es la inversa:
[[0 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


"\n\nc1=gauss_jordan(A1)\nprint('La Matriz inversa es:\n',c1)\nprint('Comprobación de que si es la inversa:')\nprint(array(dot(A1,c1),int))\n"

In [139]:
A1 = array([[ 4,-1,-1,-1 ],
           [ -1,0,3,0 ],
           [ -1,3,0,-1 ],
           [ -1,-1,0,1]], float)
n=len(A1)
B=A1.copy()
'''
if B[0,0]==0:
    B[0]=A1[1]
    B[1]=A1[0]
if B[1,1]==0:
    B[1]=A1[2]
    B[2]=A1[1]
if B[2,2]==0:
    B[2]=A1[3]
    B[3]=A1[2]
if B[3,3]==0:
    B[3]=A1[0]
    B[0]=A1[3]
'''
for i in range(n-1):
    if B[i,i]==0:
        B[i]=A1[i+1]
        B[i+1]=A1[i]
if B[-1,-1]==0:
    B[-1]=A1[0]
    B[0]=A1[-1]
print(B)

[[ 4. -1. -1. -1.]
 [-1.  3.  0. -1.]
 [-1.  0.  3.  0.]
 [-1. -1.  0.  1.]]


In [140]:
from numpy import *
from numpy.linalg import *

def gauss_jordan(A):
    A_copia=A.copy()
    n=len(A)
    c =eye(n)
    c_copia=c.copy()
    for i in range(n-1):
        if A_copia[i,i]==0:
            A_copia[i]=A1[i+1]
            A_copia[i+1]=A1[i]
            c_copia[i]=c[i+1]
            c_copia[i+1]=c[i]
    if A_copia[-1,-1]==0:
        A_copia[-1]=A1[0]
        A_copia[0]=A1[-1]
        c_copia[-1]=c[0]
        c_copia[0]=c[-1]
    for i in range(n):
        for j in range(n):
            if A_copia[i,i]!=0 and i!=j:
                multi=(A_copia[j,i]/A_copia[i,i])
                A_copia[j]=A_copia[j]-multi*A_copia[i]
                c_copia[j]=c_copia[j]-multi*c_copia[i]
    for i in range(n):
        div=A_copia[i,i]
        A_copia[i]=A_copia[i]/div
        c_copia[i]=c_copia[i]/div   
    return c_copia

In [141]:
A1 = array([[ 4,-1,-1,-1 ],
           [ -1,0,3,0 ],
           [ -1,3,0,-1 ],
           [ -1,-1,0,0]], float)
c=gauss_jordan(A1)
print('La Matriz inversa es:\n',c)
print('Comprobación de que si es la inversa:')
print(array(dot(A1,c),int))

La Matriz inversa es:
 [[ 0.11538462  0.03846154 -0.11538462 -0.46153846]
 [-0.11538462 -0.03846154  0.11538462 -0.53846154]
 [ 0.03846154  0.34615385 -0.03846154 -0.15384615]
 [-0.46153846 -0.15384615 -0.53846154 -1.15384615]]
Comprobación de que si es la inversa:
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [142]:
from numpy.linalg import *
print(A1)
print(inv(A1))

[[ 4. -1. -1. -1.]
 [-1.  0.  3.  0.]
 [-1.  3.  0. -1.]
 [-1. -1.  0.  0.]]
[[ 0.11538462  0.03846154 -0.11538462 -0.46153846]
 [-0.11538462 -0.03846154  0.11538462 -0.53846154]
 [ 0.03846154  0.34615385 -0.03846154 -0.15384615]
 [-0.46153846 -0.15384615 -0.53846154 -1.15384615]]
